name: CI

on:
  pull_request:
    paths-ignore:
      - '**.md'
  push:
    paths-ignore:
      - '**.md'
  schedule:
    - cron: '0 0 1 1-12 *'

jobs:
  compiler:
    name: TypeScript Compiler
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Use Node.js v12
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Get Yarn cache directory
      id: yarn-cache
      run: echo "::set-output name=dir::$(yarn cache dir)"
    - name: Restore cache
      uses: actions/cache@v1
      with:
        path: ${{ steps.yarn-cache.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-node-yarn-
    - name: Install dependencies
      run: yarn --frozen-lockfile
    - name: TypeScript Compiler
      run: yarn run compile:test
  lint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Use Node.js v12
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Get Yarn cache directory
      id: yarn-cache
      run: echo "::set-output name=dir::$(yarn cache dir)"
    - name: Restore cache
      uses: actions/cache@v1
      with:
        path: ${{ steps.yarn-cache.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-node-yarn-
    - name: Install dependencies
      run: yarn --frozen-lockfile
    - name: ESLint
      run: yarn run lint
